spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

cloud:
  gateway:
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
            - OPTIONS
            - HEAD

    routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/auth-service/**

      - id: blog-service
        uri: lb://blog-service
        predicates:
          - Path=/blog-service/**
